### ISSUE TITLE
 __dirname is not defined

### ISSUE THREAD

**Issue by Linxiaoxxx** [xuxiaowei-com-cn/Electron-12-Study#27]
请问我按照您的写法进行配置preload 在vue中require”electron”，一直报错“ __dirname is not defined”，是什么原因呢

**Comment by xuxiaowei-com-cn** [comment]
需要在 vue.config.js 文件中启用 nodeIntegration：
`
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
    }
  }
}
`
